<?php

namespace Banks\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BankRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BankRepository extends EntityRepository
{
}
