<?php

namespace Branches\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BranchRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BranchRepository extends EntityRepository
{
}
