version: 1
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: circleci/php:7.3-browsers-legacy
        environment:
          APP_ENV: dev
    steps:
      - run:
          name: Install project dependency
          command: |
            sudo apt-get update
            sudo apt-get install curl
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit